### ISSUE TITLE
Template format error: [/Resources/PostMethodApigEventSlackSlack]

### ISSUE THREAD

**Issue by serkanh** [section-io/pagerduty-oncall-slack-bot#1]
followed the instructions in the readme file but issuing serverless deploy result in the following error. Is api gateway required to be already in place?

```Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (11.07 MB)...
Serverless: Updating Stack...
 
  Serverless Error ---------------------------------------
 
     Template format error: [/Resources/PostMethodApigEventSlackSlack]
     Every Resources object must contain a Type member.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                 darwin
     Node Version:       6.9.1
     Serverless Version: 1.12.1
 
➜  pagerduty-oncall-slack-bot git:(master) ✗ ```

**Comment by mkochco** [comment]
Ran into the same issue.  Removed (commented out) the resources section in serverless.yml.  That just resulted in another error `The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource slack`.   Tried to resolve that error by changing "slack" to "SlackLambdaFunction" in the GetAtt declaration but that just lead to a circular dependency in the CF.  Ugh.  giving up.

**Comment by mateusz-drab-intelliflo** [comment]
Same issue here. Not even going to attempt troubleshooting, not really good at AWS.
